language: python
python:
  - "2.7"

sudo: false

addons: 
  apt: 
    packages: 
    - build-essential 
    - libgeos-c1
    - lib-geos-dev
    - libhdf5-serial-dev
    - libatlas-base-dev
    - gfortran
    - libnetcdf-dev
    - libblas3gf
    - libc6
    - libgcc1
    - libgfortran3
    - liblapack3gf
    - libumfpack5.4.0 
    - libstdc++6

# install Python dependencies
install:
  - pip install conda
  - conda init
  - deps='pip numpy scipy matplotlib basemap shapely nose coverage'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - pip install pycurl
  - pip -v install -r requirements.txt
  - pip install coveralls

# Script execution
script: 
  - python installer/setup.py build_ext -i
  - nosetests -w tests/ -v --with-coverage

# Post
after_success: 
  coveralls

